(function(root){'use strict';
const levels=['4th-easy','5th-normal','grayson'],labels={'4th-easy':'4th · Easy','5th-normal':'5th · Normal',grayson:'Grayson · Middle school'};
const types={'4th-easy':['e-priority','e-group','e-subtract','e-divide','e-left'],'5th-normal':['n-split','n-chain','n-divide','n-nested','n-left'],grayson:['g-power','g-nested','g-divide','g-negative','g-chain']};
const expertTypes=['g-expert-power','g-expert-nested','g-expert-divide','g-expert-negative','g-expert-chain'];types.grayson.push(...expertTypes);const expertRanges=[[4,15],[3,12],[3,12],[2,9]];
const ranges={'4th-easy':[[1,10],[1,10],[1,10],[1,5]],'5th-normal':[[3,18],[3,18],[2,12],[1,5]],grayson:[[2,9],[2,9],[2,8],[2,8]]};
function build(q){if(!q||!levels.includes(q.level)||!types[q.level].includes(q.type)||!['a','b','c','d'].every((k,i)=>Number.isInteger(q[k])&&q[k]>=(q.type.startsWith('g-expert')?expertRanges:ranges[q.level])[i][0]&&q[k]<=(q.type.startsWith('g-expert')?expertRanges:ranges[q.level])[i][1]))throw Error('Invalid level question');let id=0;const o=(op,left,right)=>({id:++id,op,left,right}),g=group=>({group});const {a,b,c,d}=q;
switch(q.type){case'e-priority':return o('+',a,o('×',b,c));case'e-group':return o('×',g(o('+',a,b)),c);case'e-subtract':return o('−',a*b+c,o('×',a,b));case'e-divide':return o('+',o('÷',a*b,b),c);case'e-left':return o('×',o('÷',a*b,b),c);
case'n-split':return o('−',o('×',g(o('+',a,b)),c),o('×',d,2));case'n-chain':return o('+',o('×',a,b),o('×',g(o('+',c,d)),2));case'n-divide':return o('−',o('÷',g(o('+',o('×',a,b),o('×',b,c))),b),d);case'n-nested':return o('−',o('×',a,g(o('+',b,o('×',c,d)))),b);case'n-left':return o('−',o('+',o('×',o('÷',a*b,b),c),d),c);
case'g-power':return o('+',o('−',o('^',g(o('+',a,b)),2),o('×',c,d)),b);case'g-nested':return o('+',o('×',a,g(o('−',b,g(o('+',c,d))))),o('^',c,2));case'g-divide':return o('−',o('÷',g(o('+',o('^',a,2),o('×',a,b))),a),o('×',c,d));case'g-negative':return o('+',o('×',g(o('−',a,b)),g(o('+',c,d))),o('^',b,2));case'g-expert-power':return o('+',o('−',o('÷',o('×',g(o('+',o('^',g(o('−',a,b)),2),o('^',c,3))),d),d),o('×',b,g(o('−',c,d)))),a);
case'g-expert-nested':return o('−',o('+',o('×',a,g(o('−',b,o('^',g(o('−',c,d)),2)))),o('×',g(o('+',a,b)),g(o('+',c,d)))),o('^',b,3));
case'g-expert-divide':return o('−',o('+',o('÷',g(o('−',o('^',g(o('+',a,b)),2),o('^',g(o('−',a,b)),2))),4),o('×',c,g(o('+',d,g(o('−',b,c)))))),o('^',d,2));
case'g-expert-negative':return o('−',o('+',o('×',g(o('−',o('×',g(o('−',a,c)),g(o('+',b,d))),o('^',g(o('−',b,d)),2))),2),o('^',c,3)),o('×',a,d));
case'g-expert-chain':return o('−',o('+',o('÷',g(o('−',o('^',a,3),o('×',o('×',a,b),g(o('+',c,d))))),a),o('^',g(o('−',b,d)),2)),o('×',c,g(o('−',a,g(o('+',b,d))))));
case'g-chain':return o('+',o('−',o('^',a,2),o('×',b,g(o('+',c,d)))),o('^',c,3));}}
function value(t){if(typeof t==='number')return t;if(t.group)return value(t.group);const a=value(t.left),b=value(t.right);return t.op==='+'?a+b:t.op==='−'?a-b:t.op==='×'?a*b:t.op==='÷'?a/b:a**b;}
function text(t){if(typeof t==='number')return String(t);if(t.group)return '('+text(t.group)+')';return text(t.left)+' '+t.op+' '+text(t.right);}
function describe(q){const t=build(q);return {type:q.type,expression:text(t),expected:value(t),steps:'Parentheses and nested groups first; then powers; multiply/divide left to right; add/subtract left to right.'};}
function questions(level,count=40){if(!levels.includes(level)||!Number.isInteger(count)||count<1||count>40)throw Error('Invalid level');const items=Array.from({length:count},(_,i)=>{const q={level,type:(level==='grayson'?expertTypes:types[level])[i%5]};for(const [j,k] of ['a','b','c','d'].entries()){const [min,max]=(level==='grayson'?expertRanges:ranges[level])[j];q[k]=min+Math.floor(Math.random()*(max-min+1));}return q;});for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]];}return items;}
const api={levels,labels,types,build,value,describe,questions};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.QuestLevels=api;
})(typeof globalThis!=='undefined'?globalThis:this);
