import {auth,functions,httpsCallable,onAuthStateChanged,connect,escape} from './cloud-core.js';
const kind=document.body.dataset.factKind,status=document.getElementById('cloud-status'),button=document.getElementById('cloud-connect'),count=document.getElementById('cloud-count'),rows=document.getElementById('cloud-rows'),list=httpsCallable(functions,'listFactFluency');let loading=false;
async function refresh(){if(!auth.currentUser||loading)return;loading=true;status.textContent=`Loading class results for ${auth.currentUser.email}…`;
  try{const response=await list({kind}),data=response.data.attempts.sort((a,b)=>String(b.startedAt).localeCompare(String(a.startedAt)));
    status.textContent=`Class results · ${auth.currentUser.email}`;count.textContent=`${data.length} attempt${data.length===1?'':'s'} · ${new Set(data.map(x=>x.studentId)).size} student account${new Set(data.map(x=>x.studentId)).size===1?'':'s'}`;
    rows.innerHTML=data.map(x=>`<tr><td>${escape(new Date(x.startedAt).toLocaleString())}</td><td>${escape(x.studentName)}<br><small>${escape(x.studentEmail)}</small></td><td>${escape(x.grade)}</td><td>${x.questionCount}</td><td>${x.correct}/${x.questionCount}</td><td>${x.accuracy}%</td><td>${(x.totalMs/1000).toFixed(1)}s</td><td>${x.averageCorrectMs==null?'—':(x.averageCorrectMs/1000).toFixed(1)+'s'}</td><td>${x.fastCorrect}/${x.questionCount}</td></tr>`).join('')||'<tr><td colspan="9">No cloud results for this test yet.</td></tr>';
  }catch(error){status.textContent=`Could not load class results: ${error.message}. Use the teacher Google account.`}finally{loading=false}}
button.onclick=async()=>{if(auth.currentUser){await refresh();return}try{await connect()}catch(error){status.textContent=`Sign-in did not finish: ${error.message}`}};
onAuthStateChanged(auth,user=>{rows.innerHTML='';count.textContent='';if(!user){status.textContent='Sign in with your teacher Google account to load class results.';return}button.textContent='Refresh class results';refresh()});
