(()=>{'use strict';const $=id=>document.getElementById(id),E=QuestEngine,key='dragonswood-pemdas-fluency-v1';const lands=['Moonlit Grove','Crystal Cavern','Ember Peaks','Cloud Citadel','Dragon Sanctuary'],dragons=['Moon','Crystal','Ember','Sky','Elder'];let avatar='🐉',game=null,chosen=null,sound=false,audio=null,last=null;
const safe=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const modeName=x=>QuestLevels.labels[x]||x;
function chime(win=false){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.frequency.setValueAtTime(win?740:520,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(win?1100:780,audio.currentTime+.15);gain.gain.setValueAtTime(.06,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.28);osc.start();osc.stop(audio.currentTime+.3)}catch{}}
function show(id){for(const x of ['setup','adventure','results'])$(x).hidden=x!==id;}
function expression(t){if(typeof t==='number')return `<span class="num">${t}</span>`;if(t.group)return `<span class="group"><span>(</span>${expression(t.group)}<span>)</span></span>`;return expression(t.left)+`<button class="operator" data-op="${t.id}" aria-label="${safe(t.op==='^'?'Raise to exponent':t.op)}">${t.op==='^'?'^':t.op}</button>`+(t.op==='^'?`<span class="power-exp">${expression(t.right)}</span>`:expression(t.right));}
function render(){const zone=Math.min(4,Math.floor(game.responses.length/8));$('zone-name').textContent=lands[zone];$('progress').textContent=`${game.responses.length+1} / 40`;$('gems').textContent=game.gems;$('streak').textContent=game.streak;$('task-label').textContent=`PROBLEM ${game.responses.length+1} · ${typeof game.tree==='number'?'BRIDGE RESTORED':'CHOOSE THE NEXT OPERATION'}`;$('expression').innerHTML=expression(game.tree);$('map').innerHTML=lands.map((name,i)=>`<div class="land ${i===zone?'current':i<zone?'freed':''}"><span>${i<zone?'🐉':i===zone?'✦':'🔒'}</span>${safe(name)}</div>`).join('');
 const progress=((game.responses.length%8)+game.steps/game.stepCount)/8,stones=Math.floor(progress*24);$('bridge-stones').innerHTML=Array.from({length:stones},(_,i)=>`<rect class="stone" x="${270+i*18}" y="${172-Math.sin(i/24*Math.PI)*15}" width="17" height="12" rx="3" fill="#a5ebdb" stroke="#ecffe9"/>`).join('');$('companion-art').textContent=avatar;$('companion-art').setAttribute('x',String(150+progress*540));$('story').textContent=`${lands[zone]} · Rescue the ${dragons[zone]} Dragon (${game.responses.length%8} of 8 problems finished).`;
 $('expression').querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>select(Number(b.dataset.op)));}
function load(){chosen=null;game.q=game.items[game.responses.length];game.tree=E.tree(game.q);game.steps=0;game.stepCount=E.nodes(game.tree).length;game.quest={orderErrors:0,calculationErrors:0,hints:0};game.questionTime=performance.now();game.hintedSteps=new Set();$('solve').hidden=true;$('next').hidden=true;$('hint').hidden=false;$('history').innerHTML='';$('feedback').textContent='Choose which operation to do first.';render();}
function select(id){if(typeof game.tree==='number')return;const next=E.next(game.tree);if(id!==next.id){game.quest.orderErrors++;game.streak=0;const clicked=$('expression').querySelector(`[data-op="${id}"]`);clicked?.classList.add('wrong');$('feedback').textContent='Check PEMDAS: finish parentheses, then exponents, then × / ÷ left to right, then + / − left to right.';$('streak').textContent='0';return;}chosen=next;$('expression').querySelectorAll('.operator').forEach(b=>b.classList.toggle('selected',Number(b.dataset.op)===id));$('step-label').textContent=`Solve ${E.value(chosen.left)} ${chosen.op==='^'?'to the power of':chosen.op} ${E.value(chosen.right)} = ?`;$('solve').hidden=false;$('step-answer').value='';$('step-answer').focus();$('feedback').textContent='Right operation! Now solve just this step.';}
function solve(event){event.preventDefault();if(!chosen)return;const raw=$('step-answer').value.trim();if(!/^-?\d{1,5}$/.test(raw)){$('feedback').textContent='Type an integer answer, including a minus sign if needed.';return;}const expected=E.value(chosen);if(Number(raw)!==expected){game.quest.calculationErrors++;game.streak=0;$('streak').textContent='0';$('feedback').textContent='Keep going! The operation is right. Check the calculation and try again.';$('step-answer').select();return;}
 const li=document.createElement('li');li.textContent=`${E.value(chosen.left)} ${chosen.op} ${E.value(chosen.right)} = ${expected}`;$('history').append(li);game.tree=E.reduce(game.tree,chosen.id);chosen=null;game.steps++;game.gems+=5;$('solve').hidden=true;chime();render();
 if(typeof game.tree==='number'){const firstTry=Object.values(game.quest).every(n=>n===0);game.gems+=firstTry?25:10;game.streak=firstTry?game.streak+1:0;$('gems').textContent=game.gems;$('streak').textContent=game.streak;$('feedback').textContent=`Bridge solved! ${QuestLevels.describe(game.q).expression} = ${game.tree}. ${firstTry?'First-try bonus: +25 gems!':'Practice bonus: +10 gems. You kept going!'}`;$('next').hidden=false;$('hint').hidden=true;$('next').textContent=(game.responses.length+1)%8===0?'Free the dragon →':'Next problem →';$('next').focus();}else $('feedback').textContent='Stone built! Choose the next operation in the shorter expression.';}
function hint(){if(typeof game.tree==='number')return;const n=E.next(game.tree);if(!game.hintedSteps.has(n.id)){game.quest.hints++;game.hintedSteps.add(n.id);}const b=$('expression').querySelector(`[data-op="${n.id}"]`);b.classList.add('hinted');const rule=n.op==='^'?'Exponents come before multiplication and division.':n.op==='×'||n.op==='÷'?'Multiplication and division share a level. Work left to right.':'Finish parentheses first; otherwise add or subtract left to right.';$('feedback').textContent=`Look at the glowing operation. ${rule}`;}
function next(){if(typeof game.tree!=='number')return;const correct=Object.values(game.quest).every(n=>n===0);game.responses.push({...game.q,answer:game.tree,correct,timeMs:Math.min(7200000,Math.round(performance.now()-game.questionTime)),quest:{...game.quest}});if(game.responses.length%8===0)chime(true);if(game.responses.length===40)finish();else{const freed=game.responses.length%8===0?dragons[game.responses.length/8-1]:null;load();if(freed)$('feedback').textContent=`${freed} Dragon rescued! Onward to ${lands[game.responses.length/8]}.`;}}
function finish(){const r=game.responses,correct=r.filter(x=>x.correct),record={id:game.id,student:game.student,grade:game.grade,mode:game.mode,level:game.level,count:40,startedAt:game.startedAt,totalMs:Math.min(7200000,Math.round(performance.now()-game.startTime)),correct:correct.length,accuracy:Math.round(correct.length/40*1000)/10,averageCorrectMs:correct.length?Math.round(correct.reduce((s,x)=>s+x.timeMs,0)/correct.length):null,fastCorrect:correct.filter(x=>x.timeMs<=3000).length,responses:r};last=record;let saved=[];try{saved=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(saved))saved=[];saved.push(record);localStorage.setItem(key,JSON.stringify(saved));}catch{$('feedback').textContent='Device saving failed. Download your CSV now.';}
 show('results');$('result-summary').textContent=`${record.student} · ${modeName(record.level)} · 40 problems completed · ${game.gems} gems collected.`;const sums=r.reduce((s,x)=>{for(const k of Object.keys(s))s[k]+=x.quest[k];return s},{orderErrors:0,calculationErrors:0,hints:0});$('result-stats').innerHTML=`<span>First try <b>${record.correct}/40</b></span><span>Order retries <b>${sums.orderErrors}</b></span><span>Calculation retries <b>${sums.calculationErrors}</b></span><span>Hints <b>${sums.hints}</b></span>`;$('detail').innerHTML=r.map((x,i)=>`<div><strong>${i+1}. ${safe(QuestLevels.describe(x).expression)} = ${x.answer}</strong><br>${x.correct?'First try':'Completed with practice'} · Operation retries: ${x.quest.orderErrors} · Calculation retries: ${x.quest.calculationErrors} · Hints: ${x.quest.hints}<br><small>${safe(QuestLevels.describe(x).steps)}</small></div>`).join('');window.dispatchEvent(new Event('dw-fact-finished'));$('results').scrollIntoView({behavior:'smooth',block:'start'});}
function start(){const student=$('student').value.trim();if(!student){$('setup-error').textContent='Enter your name to begin.';$('student').focus();return;}game={id:crypto.randomUUID(),student,grade:$('grade').value,level:$('level').value,mode:$('level').value==='grayson'?'with-exponents':'no-exponents',items:QuestLevels.questions($('level').value,40),responses:[],startedAt:new Date().toISOString(),startTime:performance.now(),gems:0,streak:0};$('e-label').textContent=game.mode==='with-exponents'?'Exponents · squares & cubes':'Exponents · not in this level';$('power-tip').hidden=game.mode!=='with-exponents';show('adventure');load();$('adventure').scrollIntoView({behavior:'smooth',block:'start'});}
$('download').onclick=()=>{if(!last)return;const quote=x=>'"'+String(x??'').replace(/"/g,'""')+'"';const rows=[['attempt_id','date_iso','student','grade','level','question','expression','final_answer','first_try','order_retries','calculation_retries','hints','seconds'],...last.responses.map((r,i)=>[last.id,last.startedAt,last.student,last.grade,modeName(last.level),i+1,QuestLevels.describe(r).expression,r.answer,r.correct,r.quest.orderErrors,r.quest.calculationErrors,r.quest.hints,(r.timeMs/1000).toFixed(1)])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='dragonswood-dragon-bridge-quest.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('level').onchange=()=>{$('level-description').textContent={'4th-easy':'4th Easy: small numbers and short expressions, without exponents.','5th-normal':'5th Normal: larger numbers, longer expressions, multiple groups and four or five operations.','grayson':'Grayson mode: nested grouping, squares and cubes, and positive and negative integers.'}[$('level').value];};$('start').onclick=start;$('solve').onsubmit=solve;$('next').onclick=next;$('hint').onclick=hint;$('again').onclick=()=>{show('setup');$('setup').scrollIntoView({behavior:'smooth'});};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));if(sound)chime();};document.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>{avatar=b.dataset.avatar;document.querySelectorAll('[data-avatar]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
})();
