const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const root=require('node:path').resolve(__dirname,'../..'),p=require(root+'/functions-fact-fluency/pemdas.js');
for(const mode of p.modes)for(let i=0;i<100;i++){const qs=p.questions(mode);assert.equal(qs.length,40);for(const q of qs){const d=p.describe(q,mode);const independent=vm.runInNewContext(d.expression.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll('^','**'));assert.equal(d.expected,independent);assert(Number.isInteger(d.expected)&&d.expected>=0&&d.expected<=1000);assert.equal(d.expression.includes('^'),q.type.includes('power'));}}
assert.throws(()=>p.describe({a:2,b:2,c:2,type:'power'},'no-exponents'));assert.throws(()=>p.describe({a:999,b:2,c:2,type:'priority'},'with-exponents'));
let saved;const db={collection:()=>({doc:()=>({id:'test',create:async x=>{saved=x}}),where:()=>({limit:()=>({get:async()=>({docs:[{id:'test',data:()=>saved}]})})})}),doc:()=>({get:async()=>({exists:true,data:()=>saved})})};const admin={apps:[1],firestore:()=>db};admin.firestore.FieldValue={serverTimestamp:()=>0};class HttpsError extends Error{}
const sandbox={exports:{},require:n=>n==='firebase-admin'?admin:n==='firebase-functions/v2/https'?{onCall:(_,fn)=>fn,HttpsError}:p};vm.runInNewContext(fs.readFileSync(root+'/functions-fact-fluency/index.js','utf8'),sandbox);
(async()=>{for(const mode of p.modes){const responses=p.questions(mode).map((q,i)=>({...q,answer:i===0?'':i===1?9999:p.describe(q,mode).expected,timeMs:4000,correct:true,expected:9999}));const req={auth:{uid:'test',token:{email:'jacobicusjax@gmail.com',email_verified:true}},data:{kind:'pemdas',mode,id:'test-123456',student:'Test',grade:'4',count:40,totalMs:80000,startedAt:new Date().toISOString(),responses}};const result=await sandbox.exports.submitFactFluency(req);assert.equal(result.correct,38);assert.equal(saved.mode,mode);assert.equal(saved.accuracy,95);assert.equal(saved.responses[1].correct,false);assert.notEqual(saved.responses[1].expected,9999);const list=await sandbox.exports.listFactFluency({...req,data:{kind:'pemdas'}});assert.equal(list.attempts[0].mode,mode);await assert.rejects(()=>sandbox.exports.submitFactFluency({...req,data:{...req.data,mode:'bad'}}));
 const questResponses=responses.map(r=>({...r,quest:{orderErrors:0,calculationErrors:0,hints:0}}));questResponses[2].quest.orderErrors=1;questResponses[3].quest.hints=1;const questResult=await sandbox.exports.submitFactFluency({...req,data:{...req.data,responses:questResponses}});assert.equal(questResult.correct,36);assert.equal(saved.responses[2].quest.orderErrors,1);const questList=await sandbox.exports.listFactFluency({...req,data:{kind:'pemdas'}});assert.equal(questList.attempts[0].activity,'quest');questResponses[3].quest.hints=-1;await assert.rejects(()=>sandbox.exports.submitFactFluency({...req,data:{...req.data,responses:questResponses}}));}
console.log('PASS: 8,000 generated questions, mode validation, server scoring, stats, and teacher summaries.');})();
